Generic:
    orchestrator_port: 5000

classifierv2:
    onnxmodel: ""
    trtengine: ""
    labels: ""
    batch_size: 1
    output_size: 2
    input_channel: 3
    model_type: 'FP32'

    debug_level: 10
    debug_image: 0
    frame_debug_interval: 1
    input_config:
        width: 128
        height: 128
    output_config:
        name: "fptp"
        skip: ["CAM2"]
        bboxType: ["person"]